services:
  server:
    image: ${DOCKERHUB_USERNAME}/techcore-server:latest
    container_name: techcore-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RECEIVER_EMAIL: ${RECEIVER_EMAIL}
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    expose:
      - "3000"
    networks:
      - techcore-network

  client:
    image: ${DOCKERHUB_USERNAME}/techcore-client:latest
    container_name: techcore-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - techcore-network

networks:
  techcore-network:
    driver: bridge
